[mypy]
python_version = 3.12
plugins = mypy_django_plugin.main

ignore_missing_imports = True

# Не проверяем миграции и настройки (они часто шумят)
exclude = (migrations/|config/settings\.py)

# Строгость можешь вернуть позже, пока не включай
# disallow_untyped_defs = True

[mypy.plugins.django-stubs]
django_settings_module = "config.settings"

[mypy-config.settings]
ignore_errors = True

[mypy-instagram.models]
ignore_errors = True
