# Generated by Django 6.0.2 on 2026-02-27 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ig_media_id", models.CharField(max_length=64, unique=True)),
                ("caption", models.TextField(blank=True, default="")),
                ("media_type", models.CharField(blank=True, default="", max_length=32)),
                ("media_url", models.URLField(blank=True, default="")),
                ("permalink", models.URLField(blank=True, default="")),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("username", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ig_comment_id", models.CharField(blank=True, default="", max_length=64)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="instagram.post"
                    ),
                ),
            ],
        ),
    ]
