# Generated by Django 6.0.2 on 2026-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="permalink",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
