# Generated by Django 6.0.2 on 2026-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0002_alter_post_media_url_alter_post_permalink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="media_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="permalink",
            field=models.TextField(blank=True, default=""),
        ),
    ]
